### PR TITLE
Do not try to send notification e-mail if destination address is not available

### PR DESCRIPTION
**Pull request by rafaelbco**
Tests are passing.

### CODE REVIEW

**Comment by tschorr** [comment]
Merged. Thank you!

**Comment by rafaelbco** [comment]
You're welcome. I would appreciate a release :smile:

**Comment by tschorr** [comment]
I see. I'm a bit reluctant because https://github.com/Haufe-Lexware/hl.plone.boardnotifications/commit/11abd4f325b11e8c67ecd8763b45121a4a2ad80c will break existing installations (although it's a real performance improvement if you have a lot of subscriptions). I could do a release based on a branch before that change and this PR within the next couple of days, otherwise it'll take me some more time to document the migration. What do you think?

**Comment by rafaelbco** [comment]
If it will cause this trouble then I think It's not necessary. Do a proper release when you think it's OK. Meanwhile I can make an internal release. Thanks !

**Comment by tschorr** [comment]
released in version 1.1. Sorry for the delay.

**Comment by rafaelbco** [comment]
Thanks !

Rafael Oliveira

**Pull request merged**
